# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/floydwiz_technologies/Primebook-4G/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Primebook-4G)

endif
